Add support for overlay /configs, rename ENABLE_OVERLAY_FOR_SYSTEM_PARTITION

diff --git a/init b/init
--- a/init
+++ b/init
@@ -12,6 +12,7 @@ WZMINI_INIT_FILE_NEWROOT=/opt/wz_mini/etc/init.d/wz_init.sh
 WZMINI_OVERLAY_FILE=/sdcard/wz_mini-overlay.img
 WZMINI_OVERLAY_EMPTY_COMPRESSED_FILE=/sdcard/wz_mini/overlay_empty.img.gz
 WZMINI_KERNEL_MODULE_PATH=/sdcard/wz_mini/lib/modules/3.10.14__isvp_swan_1.0__
+STOCK_INITD_RCS=/newroot/etc/init.d/rcS
 
 
 # devtmpfs does not get automounted for initramfs
@@ -58,6 +59,7 @@ mkdir /newroot
 mount -t squashfs /dev/mtdblock2 /stock_rootfs
 mount -t vfat /dev/mmcblk0p1 /sdcard -o rw,umask=0000,dmask=0000
 mount -t vfat /dev/mmcblk0p1 /sdcard2 -o rw,umask=0000,dmask=0000
+cp /sdcard/wz_mini/bin/busybox /tmp/busybox
 
 fsck_sdcard() {
 	echo "Running fsck on SD Card"
@@ -114,7 +116,7 @@ mount_overlay_rootfs() { # Mount rootfs as overlay
 		# Create overlay image from compressed empty overlay image file
 		if [[ -f $WZMINI_OVERLAY_EMPTY_COMPRESSED_FILE ]]; then
 		echo "Decompressing $WZMINI_OVERLAY_EMPTY_COMPRESSED_FILE"
-			/sdcard/wz_mini/bin/busybox gzip -d -k -c $WZMINI_OVERLAY_EMPTY_COMPRESSED_FILE > $WZMINI_OVERLAY_FILE || { echo "Failed to decompress $WZMINI_OVERLAY_EMPTY_COMPRESSED_FILE" ; return 1 ; }
+			/tmp/busybox gzip -d -k -c $WZMINI_OVERLAY_EMPTY_COMPRESSED_FILE > $WZMINI_OVERLAY_FILE || { echo "Failed to decompress $WZMINI_OVERLAY_EMPTY_COMPRESSED_FILE" ; return 1 ; }
 		else
 			{ echo "$WZMINI_OVERLAY_EMPTY_COMPRESSED_FILE is missing" ; return 1 ; }
 		fi
@@ -146,14 +148,21 @@ mount_overlay_rootfs() { # Mount rootfs as overlay
 	mount --move /overlay /newroot/overlay
 }
 
-mount_overlay_system() { # Mount /system as overlay
+mount_overlay_driver() { # Mount /system as overlay
 	echo "Mounting /system as overlay"
 	mkdir -p /newroot/overlay_mnt/stock_system
-	mkdir -p /newroot/overlay_mnt/system_overlay
+	mkdir -p /newroot/overlay_mnt/system_overlay-upper
 	mount -t squashfs /dev/mtdblock3 /newroot/overlay_mnt/stock_system
-	mount -t overlayfs overlayfs -o lowerdir=/newroot/overlay_mnt/stock_system,upperdir=/newroot/overlay_mnt/system_overlay /newroot/system
+	mount -t overlayfs overlayfs -o lowerdir=/newroot/overlay_mnt/stock_system,upperdir=/newroot/overlay_mnt/system_overlay-upper /newroot/system
 }
 
+mount_overlay_configs() { # Mount /configs as overlay
+	echo "Mounting /configs as overlay"
+	mkdir -p /newroot/overlay_mnt/stock_configs
+	mkdir -p /newroot/overlay_mnt/configs_overlay-upper
+	mount -t jffs2 /dev/mtdblock6 /newroot/overlay_mnt/stock_configs
+	mount -t overlayfs overlayfs -o lowerdir=/newroot/overlay_mnt/stock_configs,upperdir=/newroot/overlay_mnt/configs_overlay-upper /newroot/configs
+}
 
 
 ##### ERROR CHECKING AND DEBUGGING #####
@@ -179,6 +188,7 @@ fi
 if [[ "$DEBUG_INITRAMFS_ENABLED" == "true" ]]; then
 	echo "DEBUG_INITRAMFS_ENABLED value is true"
 	echo "Starting initramfs debug mode"
+	exec &>/dev/ttyS1
 	exec /bin/sh
 else
 	echo "DEBUG_INITRAMFS_ENABLED value is false"
@@ -189,11 +199,19 @@ fi
 if [[ "$ENABLE_OVERLAY_FOR_ROOTFS" == "true" ]]; then
 	echo "ENABLE_OVERLAY_FOR_ROOTFS value is true"
 	if mount_overlay_rootfs; then
-		if [[ "$ENABLE_OVERLAY_FOR_SYSTEM_PARTITION" == "true" ]]; then # Mount /system as overlay if only mounting rootfs as overlay succeeds
-			echo "ENABLE_OVERLAY_FOR_SYSTEM_PARTITION value is true"
-			mount_overlay_system
+		if [[ "$ENABLE_OVERLAY_FOR_DRIVER_PARTITON" == "true" ]]; then # Mount /system as overlay if only mounting rootfs as overlay succeeds
+			echo "ENABLE_OVERLAY_FOR_DRIVER_PARTITON value is true"
+			mount_overlay_driver
 		else
-			echo "ENABLE_OVERLAY_FOR_SYSTEM_PARTITION value is false"
+			echo "ENABLE_OVERLAY_FOR_DRIVER_PARTITON value is false"
+		fi
+		if [[ "$ENABLE_OVERLAY_FOR_CONFIGS_PARTITION" == "true" ]]; then # Mount /configs as overlay if only mounting rootfs as overlay succeeds
+			echo "ENABLE_OVERLAY_FOR_CONFIGS_PARTITION value is true"
+			/tmp/busybox sed -i 's~mount\ -t\ jffs2\ /dev/mtdblock6\ /configs~#mount\ -t\ jffs2\ /dev/mtdblock6\ /configs~g' $STOCK_INITD_RCS
+			mount_overlay_configs
+		else
+			echo "ENABLE_OVERLAY_FOR_CONFIGS_PARTITION value is false"
+			/tmp/busybox sed -i 's~#mount\ -t\ jffs2\ /dev/mtdblock6\ /configs~mount\ -t\ jffs2\ /dev/mtdblock6\ /configs~g' $STOCK_INITD_RCS
 		fi
 	else
 		echo "Mounting rootfs as overlay failed, falling back to wz_mini without overlay image"
