v2 flashing modifications

diff --git a/init b/init
--- a/init
+++ b/init
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-exec 1> /tmp/wz_mini_initramfs.log 2>&1
+exec 1> /tmp/wz_mini_u_boot_initramfs.log 2>&1
 
 set -x
 
@@ -27,97 +27,91 @@ if [ -b /dev/mtdblock10 ]; then
 	#T20: Insert required delay for sd card init
 	sleep 3
 
+	if ! [ -d /sys/class/gpio/gpio38 ]; then
+		echo 38 > /sys/class/gpio/export
+		echo out > /sys/class/gpio/gpio38/direction
+		echo 1 > /sys/class/gpio/gpio38/value
+	fi
+
+	if ! [ -d /sys/class/gpio/gpio39 ]; then
+		echo 39 > /sys/class/gpio/export
+		echo out > /sys/class/gpio/gpio39/direction
+		echo 1 > /sys/class/gpio/gpio39/value
+	fi
+
+	/led.sh &
+
+	mkdir -p /sdcard
+	mount -t vfat /dev/mmcblk0p1 /sdcard -o rw,umask=0000,dmask=0000
+
+	cp /mtd0_v2_latest.bin.gz /tmp
+	cd /tmp
+	/bin/busybox gzip  -d mtd0_v2_latest.bin.gz
+	/bin/busybox dd if=/dev/mtd0 of=/tmp/mtd0_orig.bin
+
+	MTD0_ORIG=$(/bin/busybox md5sum /tmp/mtd0_orig.bin)
+
+
+	check_u_boot_pre_flash() {
+		if [[ "$(/bin/busybox md5sum /dev/mtd0)" == *"9a4dc35e081645f0b87baf7f8636ef8d"* ]]; then
+			echo "u-boot new version match! exit"
+			sync
+			restart_device
+		else
+			flash_u_boot
+		fi
+	}
+
+	check_u_boot_post_flash() {
+		if [[ "$(/bin/busybox md5sum /dev/mtd0)" == *"9a4dc35e081645f0b87baf7f8636ef8d"* ]]; then
+			echo "flash OK"
+			erase_kernel
+		else
+			echo "flashsum doesn't match"
+			restore_stock_u_boot
+		fi
+	}
+
+	flash_u_boot() {
+		/bin/busybox flashcp -v /tmp/mtd0_v2_latest.bin /dev/mtd0
+		sync
+		sleep 1
+		check_u_boot_post_flash
+	}
+
+	check_stock_u_boot() {
+		if [[ "$(/bin/busybox md5sum /dev/mtd0)" == *"$MTD0_ORIG"* ]]; then
+			echo "restored stock OK"
+			sync
+			sleep 1
+			erase_kernel
+		else
+			echo "fail"
+			erase_kernel
+		fi
+	}
+
+	restore_stock_u_boot() {
+		/bin/busybox flashcp -v /tmp/mtd0_orig.bin /dev/mtd0
+		sync
+		sleep 1
+		check_stock_u_boot
+	}
+
+	erase_kernel() {
+		/bin/busybox flash_eraseall /dev/mtd1
+		restart_device
+	}
+
+	restart_device() {
+		exec busybox switch_root / /tmp/null
+	}
+
+	check_u_boot_pre_flash
+
 else
 	echo "Not T20"
-fi
-
-if ! [ -d /sys/class/gpio/gpio38 ]; then
-	echo 38 > /sys/class/gpio/export
-	echo out > /sys/class/gpio/gpio38/direction
-	echo 1 > /sys/class/gpio/gpio38/value
-fi
-
-if ! [ -d /sys/class/gpio/gpio39 ]; then
-	echo 39 > /sys/class/gpio/export
-	echo out > /sys/class/gpio/gpio39/direction
-	echo 1 > /sys/class/gpio/gpio39/value
-fi
-
-mkdir -p /sdcard
-mount -t vfat /dev/mmcblk0p1 /sdcard -o rw,umask=0000,dmask=0000
-
-if [ -f /sdcard/wz_mini/wz_mini.conf ]; then
-        source /sdcard/wz_mini/wz_mini.conf
-fi
-
-
-initram_init() {
-
-mkdir /wz
-mount -t squashfs /dev/mtdblock2 /wz
-
-if [[ "$ENABLE_FSCK_ON_BOOT" == "true" ]]; then
-	/led.sh &
-	led_pid="$!"
-	cp /sdcard/wz_mini/bin/fsck.vfat /tmp/fsck.vfat
-	umount /sdcard
-	/tmp/fsck.vfat -a -v /dev/mmcblk0p1
-	rm -f /tmp/fsck.vfat
-	sync
-	mount -t vfat /dev/mmcblk0p1 /sdcard -o rw,umask=0000,dmask=0000
-	kill $led_pid
-	echo 1 > /sys/class/gpio/gpio39/value
-	echo 0 > /sys/class/gpio/gpio38/value
-fi
-
-if [ ! -f /sdcard/wz_mini/etc/init.d/wz_init.sh ]; then
-
-	echo "wz_mini not found, booting stock"
-
-	mount --move /dev /wz/dev
-	mount --move /sys /wz/sys
-	mount --move /proc /wz/proc
-
-	cp /tmp/wz_mini_initramfs.log /sdcard/wz_mini_initramfs.log
-
-	umount /sdcard
-
-	exec busybox switch_root /wz /linuxrc
-
-else
-
-	echo "Loading wz_mini..."
-
-	mkdir -p /wz/dev
-	mkdir -p /wz/sys
-
-
-	mount --move /dev /wz/dev
-	mount --move /sys /wz/sys
-	mount --move /proc /wz/proc
-
-	#mkdir -p /wz/media/mmc
-	mount --move /sdcard /wz/opt
-
-	cp /tmp/wz_mini_initramfs.log /wz/opt/wz_mini_initramfs.log
-
-	#exec busybox switch_root /wz /linuxrc
-	exec busybox switch_root /wz /opt/wz_mini/etc/init.d/wz_init.sh
-
-fi
-
-}
-
-if [ -f /sdcard/wz_mini/wz_mini.conf ]; then
-
-	source /sdcard/wz_mini/wz_mini.conf
-
-	if [[ "$DEBUG_INITRAMFS_ENABLED" == "true" ]]; then
-		exec /bin/sh
-	else
-		echo "initramfs debug disabled"
-		initram_init
+	exec busybox switch_root / /tmp/null
+	exit 1
 	fi
-else
-		initram_init
-fi
+
