Prioritize DEBUG_INITRAMFS_ENABLED so it stil works if wz_init.sh is missing

diff --git a/init b/init
--- a/init
+++ b/init
@@ -154,20 +154,8 @@ if ! [ -f $WZMINI_CONFIG_FILE ]; then
 	boot_stock
 fi
 
-if ! [ -f $WZMINI_INIT_FILE ]; then
-	echo "$WZMINI_INIT_FILE is missing, falling back to stock firmware"
-	boot_stock
-fi
-
 /tmp/busybox dos2unix $WZMINI_CONFIG_FILE
 source $WZMINI_CONFIG_FILE
-
-if [[ "$ENABLE_FSCK_ON_BOOT" == "true" ]]; then
-	echo "ENABLE_FSCK_ON_BOOT value is true"
-	fsck_sdcard
-else
-	echo "ENABLE_FSCK_ON_BOOT value is false"
-fi
 
 if [[ "$DEBUG_INITRAMFS_ENABLED" == "true" ]]; then
 	echo "DEBUG_INITRAMFS_ENABLED value is true"
@@ -178,6 +166,17 @@ else
 	echo "DEBUG_INITRAMFS_ENABLED value is false"
 fi
 
+if [[ "$ENABLE_FSCK_ON_BOOT" == "true" ]]; then
+	echo "ENABLE_FSCK_ON_BOOT value is true"
+	fsck_sdcard
+else
+	echo "ENABLE_FSCK_ON_BOOT value is false"
+fi
+
+if ! [ -f $WZMINI_INIT_FILE ]; then
+	echo "$WZMINI_INIT_FILE is missing, falling back to stock firmware"
+	boot_stock
+fi
 
 ##### MOUNTING #####
 if [[ "$ENABLE_OVERLAY_FOR_ROOTFS" == "true" ]]; then
